### ISSUE TITLE
hh-ru_scrapper.ipynb doesn't work

### ISSUE THREAD

**Issue by iamtodor** [avk0/skills_graph#3]
Привет! Пытался запустить ноутбук ничего не меняя - на второй ячейке ошибка:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-b357d7b7a4c5> in <module>
      3 
      4 for page_res_json in res_all:
----> 5     for i in range(page_res_json[0]['per_page']):
      6         vac_id = page_res_json[0]['items'][i]['id']
      7         vac_res = ses.get(f'https://api.hh.ru/vacancies/{vac_id}')

KeyError: 0
```

**Comment by iamtodor** [comment]
Так же запускал `hh-ru_scraper.py` - не понятно дальше как получить статистику. Все результаты в консоли

**Comment by iamtodor** [comment]
fixed: https://github.com/avk0/skills_graph/pull/4

**Comment by avk0** [comment]
Спасибо за замечание. Почистил ipython ноутбуки, последние изменения залил в ветку repo_cleaning. Сейчас оба ноутбука должны работать.

**Comment by iamtodor** [comment]
@avk0 спасибо! можно ли связаться с тобой в телеграме? есть еще пару вопросиков)

**Comment by avk0** [comment]
Да, пиши :) t.me/threebirds
